#VPC - isolated virtual private network
resource "aws_vpc" "my-vpc" {
  cidr_block = var.vpc_cidr
  enable_dns_hostnames = true
}

#Fetch availability zone
data "aws_availability_zones" "az" {
  state = "available"
}

#Subent - VPC divided into small network 
resource "aws_subnet" "my-subnet" {
  cidr_block              = var.subnet_cidr
  vpc_id                  = aws_vpc.my-vpc.id
  map_public_ip_on_launch = true
  availability_zone       = data.aws_availability_zones.az.names[0]
}

#Internet Gateway - connects VPC to public internet
resource "aws_internet_gateway" "gw" {
  vpc_id = aws_vpc.my-vpc.id
}

#Route table - route traffic from subnet to internet gateway
resource "aws_route_table" "rt" {
  vpc_id = aws_vpc.my-vpc.id
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.gw.id
  }
}

#Link route table to subnet
resource "aws_route_table_association" "rt-association" {
  subnet_id      = aws_subnet.my-subnet.id
  route_table_id = aws_route_table.rt.id
}

#AWs security group to allow traffic
resource "aws_security_group" "sg" {
  vpc_id = aws_vpc.my-vpc.id
  dynamic "ingress" {
    for_each = var.allowed_ports
    content {
      description = "Allow port ${ingress.value}"
      from_port   = ingress.value
      to_port     = ingress.value
      protocol    = "tcp"
      cidr_blocks = ["0.0.0.0/0"]
    }
  }
  egress {
    description = "Allow all outbound"
    cidr_blocks = ["0.0.0.0/0"]
    from_port   = 0
    protocol    = "-1"
    to_port     = 0
  }
}

#Adding key generated by ssh-genkey
resource "aws_key_pair" "my_key_pair" {
  key_name   = "terra-key"
  public_key = file("~/.ssh/terra-key.pub")
}

#aws instance - creating ec2 instance in our PVC
resource "aws_instance" "my-ec2" {
  for_each = var.instance_type
  ami = each.value.ami #iterate through each intance and give ami value
  instance_type               = each.value.i_type
  key_name                    = aws_key_pair.my_key_pair.key_name
  subnet_id                   = aws_subnet.my-subnet.id
  vpc_security_group_ids      = [aws_security_group.sg.id]
  associate_public_ip_address = true
  tags =  {
    Name = each.key
    Project = var.project_name
  }
  lifecycle {
    create_before_destroy = true
  }
}
